"use client"

import React from 'react';
import { AlertTriangle, ArrowLeft, BarChart3, Info, Scale, ShieldCheck, Zap } from 'lucide-react';
import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Separator } from '@/components/ui/separator';

export default function DisclaimerPage() {
  return (
    <div className="min-h-screen bg-[#050507] text-white font-sans selection:bg-indigo-500/30">
      <header className="h-20 glass border-b border-white/5 flex items-center justify-between px-10 sticky top-0 z-50">
        <div className="flex items-center gap-10">
          <Link href="/" className="flex items-center gap-3 hover:opacity-80 transition-opacity">
            <div className="w-10 h-10 rounded-xl bg-indigo-600 flex items-center justify-center shadow-lg shadow-indigo-600/20">
              <BarChart3 className="text-white h-6 w-6" />
            </div>
            <span className="text-xl font-bold tracking-tight">AutoStat AI</span>
          </Link>
        </div>
        <Link href="/">
          <Button variant="outline" className="border-white/10 hover:bg-white/5 rounded-full px-6 text-xs uppercase tracking-widest font-bold">
            <ArrowLeft className="mr-2 h-3.5 w-3.5" /> Back to Home
          </Button>
        </Link>
      </header>

      <main className="p-10 max-w-[900px] mx-auto py-20 space-y-16">
        <div className="space-y-4">
          <h1 className="text-5xl font-black uppercase tracking-tighter">Disclaimer</h1>
          <p className="text-white/40 font-medium">Professional Disclosure & Accountability</p>
        </div>

        <section className="space-y-12">
          <Card className="bg-red-500/5 border-red-500/20 rounded-[2rem] p-10">
            <div className="flex items-start gap-6">
              <AlertTriangle className="h-10 w-10 text-red-400 shrink-0" />
              <div className="space-y-4">
                <h2 className="text-2xl font-bold text-red-200">Informational Purposes Only</h2>
                <p className="text-red-100/60 text-lg leading-relaxed font-medium">
                  AutoStat AI provides analytical insights for informational and educational purposes only. Results generated by the platform should not be considered financial, legal, medical, investment, or other professional advice.
                </p>
              </div>
            </div>
          </Card>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            <div className="space-y-4">
              <h3 className="text-xl font-bold flex items-center gap-2"><Zap className="text-indigo-500 h-5 w-5" /> Forecasting Limitations</h3>
              <p className="text-white/60 leading-relaxed">
                Forecasts and projections generated by our predictive models are mathematical estimates based on historical data sequences. They are not guarantees of future outcomes and should be treated with appropriate statistical skepticism.
              </p>
            </div>
            <div className="space-y-4">
              <h3 className="text-xl font-bold flex items-center gap-2"><ShieldCheck className="text-indigo-500 h-5 w-5" /> AI Inaccuracies</h3>
              <p className="text-white/60 leading-relaxed">
                AI-generated insights and executive summaries are produced by large language models. While highly advanced, these models can produce inaccuracies, hallucinations, or misinterpreted statistical patterns.
              </p>
            </div>
          </div>

          <div className="space-y-4">
            <h3 className="text-xl font-bold flex items-center gap-2"><Scale className="text-indigo-500 h-5 w-5" /> User Responsibility</h3>
            <p className="text-white/60 leading-relaxed">
              Users are solely responsible for validating all analytical results and insights before making decisions based on them. We recommend verifying key findings through manual statistical audits or consulting with domain experts.
            </p>
          </div>

          <Card className="bg-white/5 border-white/10 rounded-3xl p-8">
            <div className="flex items-center gap-4 mb-4">
              <Info className="h-6 w-6 text-indigo-500" />
              <h4 className="font-bold">Platform Status</h4>
            </div>
            <p className="text-sm text-white/40 leading-relaxed">
              AutoStat AI is a data analytics and reporting platform designed to assist users in exploring and understanding datasets through statistical analysis, forecasting, visualization, and AI-assisted insights.
            </p>
          </Card>
        </section>

        <Separator className="bg-white/5" />
        
        <footer className="py-8">
           <p className="text-[10px] font-bold text-white/40 uppercase tracking-widest">© 2026 AutoStat AI • Built by Joshua Ziegen Paul</p>
        </footer>
      </main>
    </div>
  );
}
